### ISSUE TITLE
Fix profile link from !players

### ISSUE THREAD

**Issue by ghost** [LVPlayground/nuwani#8]
[13:05] <%[]Ricky92> !players Forge
[13:05] <Nuwani> Forge has been online for 3 hours and 49 minutes. The player has killed 71 people so far, and has died 27 times themself, which makes a ratio of 2.63. Forge is a player on Las Venturas Playground, and was last ingame at 2015-12-28 13:50:13. This player is a VIP. - http://profile.sa-mp.nl/Forge

The link in question redirects to https://sa-mp.nl/players/index.html

Could this be fixed so the link goes where it should do?

**Comment by debuggest3** [comment]
Does the link work with https?

Op ma 28 dec. 2015 om 14:12 schreef GrannyLVP notifications@github.com

**Comment by BeanerLVP** [comment]
This is probably because the website isn't updating properly. Forge doesn't appear to be registered (try searching for his profile). Links to older profiles work.
The individual rankings for stats aren't updating either.

**Comment by ghost** [comment]
@BeanerLVP seems to be correct here. My profile, for example, works fine from the !players output. 

As briefly discussed on IRC, the fact that "Forge" isn't registering with our website properly looks to be related to our replication setup (or at least, that's how I understood it).

**Comment by mblokker** [comment]
Is this still happening? I can't seem to find any user called 'Forge'.

**Comment by ghost** [comment]
I think that's an old issue from a couple months back where sync between the gameserver/website was borked
