### ISSUE TITLE
Tempmod, is_vip_mod, bank account cleanup

### ISSUE THREAD

**Issue by ghost** [LVPlayground/nuwani#9]
Now that the moderator platform has been removed from the game mode, we don't have a need for !givetempmod anymore. Can this be removed/disabled, and updated in our Nuwani2 documentation topic? Temp mods also needs to be removed from !ingamecrew

Furthermore, is_vip_mod needs to be removed from !supported as it's no longer a part of the game mode, as does plus_points, money_bank_limit, pro_account, platinum_account and platinum_earnings.

Ref: https://forum.sa-mp.nl/showthread.php?tid=32596

**Comment by debuggest3** [comment]
I've created https://github.com/LVPlayground/bot-saber/issues/3 for temp mods in !ingamecrew.

**Comment by mblokker** [comment]
https://github.com/LVPlayground/bot-nuwani/commit/d1b0c04afab1d980f38321078925dea854850908

Documentation will be updated later today.
